### ISSUE TITLE
How to run this as a HA addon

### ISSUE THREAD

**Issue by trullock** [wez/pview#1]
I'm technical but not experienced with this process.

How can I get this up and running within HA supervisor as an Addon?

My hardware is an ODROID N2

Thanks

**Comment by wez** [comment]
I don't have a way to run and test in that configuration, so I've never tried it.
If you're willing, I'd appreciate it if you could have a go and share what you find!

* https://developers.home-assistant.io/docs/add-ons/tutorial/ has a tutorial to follow
* There is a `Dockerfile` already present in this repo

There will need to be some way to convey the mqtt broker and potentially auth into the addon.
I run this via the docker compose file I mention in the readme, with a `.env` file to populate the
environment. I'm not sure that works in the hass add-on environment.

**Comment by trullock** [comment]
Yep I'll give it a try later

I've go no expereince with rust/cargo. If you can get the build system for the various arch's up and running that would be great.

Happy to collaborate on a single repro

**Comment by wez** [comment]
Thanks; I'd appreciate your input. I don't have a hass deployment that will run with add-ons, and I don't have arm hardware to validate on.

I think that the `Dockerfile` should be good to build and run on arm but I don't have a way to verify it. I did put some time into making `docker buildx build --platform linux/arm/v7 .` run to completion (it's a slow process because it runs under qemu), so hopefully there won't be much to wrangle.

**Comment by trullock** [comment]
I'm testing locally on x64 but will need an arm64 binary to deploy to HA proper

**Comment by trullock** [comment]
FYI here's where I'm working. 

currently WIP https://github.com/trullock/pview-addon

**Comment by trullock** [comment]
I need you to publish your image with the arch in the name please, e.g.

ghcr.io/wez/pview-amd64:latest

if you can build an arm64 whilst youre at it too please

thanks

**Comment by wez** [comment]
I just pushed https://github.com/wez/pview/pkgs/container/pview-no-tls which is a multi-arch image (amd64, arm64, and armv7). That build has no TLS support in the MQTT client, which is "fine" because this project doesn't currently expose configuration for turning on TLS to talk to an MQTT broker.  Getting a TLS build on the other platforms is currently too much of a PITA because GitHub actions doesn't provide native arm builder machines.

So, in your `config.yaml`, I think you want to switch to: `image: "ghcr.io/wez/pview-no-tls"` for now, and see how you go!

**Comment by trullock** [comment]
Ughh to use this as an addon you need to build against a compatible base image

https://github.com/home-assistant/docker-base/pkgs/container/aarch64-base

Gonna need you to build against these base containers, or if the container is just hosting the binary, publish the binary somewhere so i can apt-get it or whatever

**Comment by wez** [comment]
The pview containers are `FROM scratch` containers, so they basically only have the binaries in them.

I think you can probably do something like this in your add-on Dockerfile to get them into your image:

```Dockerfile
FROM ghcr.io/wez/pview-no-tls:latest as pview
COPY --from=pview /app/pview /app/pview
```

**Comment by wez** [comment]
~~You may need to use `ghcr.io/wez/pview-no-tls:main` temporarily, until https://github.com/wez/pview/actions/runs/7342350616 finishes running~~

EDIT: this is up now

**Comment by trullock** [comment]
Thanks

So doing this:

```
FROM ghcr.io/wez/pview-no-tls:latest as pview
COPY --from=pview /app/pview /app/pview
```

Gets me stuck with the below. Url looks correct so don't know if HA is blocking the request or something...

> invalid from flag value pview: pull access denied for pview, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Anyway, Here are the relevant docs if you want to try for yourself. Going to bed now, I'm 8/9 hours ahead of you.

https://developers.home-assistant.io/docs/add-ons/tutorial
https://developers.home-assistant.io/docs/add-ons/configuration/

**Comment by wez** [comment]
hmm, does `docker pull ghcr.io/wez/pview-no-tls:latest` work ok there? I wonder if maybe there's some caching from earlier because that `:latest` tag wasn't being populated until that job ran. Maybe when you next come back to this it will just work? :-)

**Comment by wez** [comment]
I figured out the error message; docker doesn't want `FROM XXX as something` as the last `FROM` in a file, because that last one is the source of the final image layer, so switching them around fixed things up.

I got enough of a test environment set up that I could boot an addon that can't talk to anything real on my network, and that is now pushed here to this repo.

So I think you can pick this up by adding this repo as a custom repo in your addon store:

* Go to the addon store
* In the top right, click the `...` and then choose Repositories
* In the `Add` box, enter `https://github.com/wez/pview`
* Click the `Add` button
* Now you should see this repo and its addon, and install it

**Comment by trullock** [comment]
Got your addon installed, gets this far:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
PV_MQTT_PORT=1883
PV_MQTT_HOST=ZZZ
PV_MQTT_USER=XXX
PV_HUB_IP=YYY
[2023-12-28T09:23:55 INFO  pview::commands::serve_mqtt] http server addr is 0.0.0.0:32873
[2023-12-28T09:24:01 INFO  pview::commands::serve_mqtt] Version 2023.12.27-5b62caa6. Waiting for mqtt and pv messages
```

I have a `pv2mqtt` entry in mosquitto, and I can see my blinds in HA.

I'll give it a whirl

**Comment by trullock** [comment]
As an addon, this is working. So will close this. thanks
